name: Load Test (20 matrix)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Target URL to test'
        required: true
        default: "https://example.com"
        type: string
      method:
        description: 'HTTP method: GET or POST'
        required: true
        default: 'GET'
        type: choice
        options:
          - 'GET'
          - 'POST'
      requests:
        description: 'Requests to send per matrix (x/20)'
        required: true
        default: '10000'
        type: string
      max_concurrency:
        description: 'Maximum number of concurrent requests'
        required: true
        default: '1000'
        type: string
      timeout:
        description: 'Time to wait for response'
        required: true
        default: '10s'
        type: string
jobs:
  load-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build load tester
        run: go build -o load-tester
      - name: Run load test
        run: |
          ./load-tester \
            --url ${{ github.event.inputs.url }} \
            --method ${{ github.event.inputs.method }} \
            --requests ${{ github.event.inputs.requests }} \
            --max-concurrency ${{ github.event.inputs.max_concurrency }} \
            --timeout ${{ github.event.inputs.timeout }} \
            --status-interval 5s \
            --verbose
